name: falakapp
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.1.3

  cupertino_icons: ^0.1.2
  http: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
      - assets/
